# Generated by Django 5.1 on 2025-11-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_investech', '0002_inversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('compra', 'Compra'), ('venta', 'Venta'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='app_investech.usuario')),
            ],
        ),
    ]
